### PR TITLE
Fix add overlapping session bug

### LINKED ISSUE #110: Add session allows adding of session onto existing session slot.
Add session allows us to create a session on an existing session slot.
image

### PR DESCRIPTION
**Pull request by chwoozy**
Added a check that considers any overlaps in the entire period of a session.

Changed `Duration`'s value from `String` to `int`.

Fixes #110

### CODE REVIEW

File: src/main/java/seedu/address/model/AddressBook.java [hunk 1]
```diff
@@ -142,6 +142,14 @@ public boolean hasSession(Session session) {
...
 
+    /**
+     * Returns true if session {@code Session} overlaps with any session belonging to any student
+     * in the unique student list
+     */
+    public boolean hasOverlappingSession(Session session) {
+        return students.hasOverlappingSession(session);
+    }
+
     //// util methods
```
Comment (enhao25) [inline src/main/java/seedu/address/model/AddressBook.java]: Actually outside of scope, but this comment here seems abit unnecessary with ////, I think we could just use // instead, so that it won't be flagged as a "bug" during PE dry run.

**Review by enhao25 — APPROVED** [review]
Yeap LGTM. However, there is something that I noticed when checking out the PR and testing it which is outside of the scope of this issue. The duration class allows a duration of 0. Do you think it would be better if we only allow value > 0.

File: src/main/java/seedu/address/model/Model.java [hunk 2]
```diff
@@ -106,6 +106,11 @@
      */
     boolean hasSession(Session session);
 
+    /**
+     * Returns true if {@code session} overlaps with any session in any of the students in the unique student list
```
Comment (samleewy) [inline src/main/java/seedu/address/model/Model.java:110]: Perhaps `{@code Session}`?

File: src/main/java/seedu/address/model/AddressBook.java (hunk 1 above)
Comment (chwoozy) [reply src/main/java/seedu/address/model/AddressBook.java]: Were these from AB3? Okay I'll remove the extra forward slashes.

**Comment by chwoozy** [comment]
> Yeap LGTM. However, there is something that I noticed when checking out the PR and testing it which is outside of the scope of this issue. The duration class allows a duration of 0. Do you think it would be better if we only allow value > 0.

Good point, I'll add a data validation for this!

**Review by samleewy — APPROVED** [review]
LGTM! Just minor changes required in docs.

File: src/main/java/seedu/address/model/Model.java (hunk 2 above)
Comment (chwoozy) [reply src/main/java/seedu/address/model/Model.java:110]: Thanks for spotting! 🙏🏻 arigathanks

File: src/main/java/seedu/address/model/session/Session.java [hunk 3]
```diff
@@ -43,6 +43,19 @@ public Fee getFee() {
         return fee;
     }
 
+    /**
+     * Checks if the {@code Session} slot overlaps with another session.
+     * @param otherSession the other session that is compared to.
+     */
+    public boolean isOverlapping(Session otherSession) {
```
Comment (nowknowing) [inline src/main/java/seedu/address/model/session/Session.java:50]: Coming up, will have to edit this to serve Recurring Sessions as well.
TODO for me

Comment (chwoozy) [reply src/main/java/seedu/address/model/session/Session.java:50]: Gotcha
