### PR TITLE
Fix Student/SessionBuilder bug

### LINKED ISSUE #109: Issue with session builder
Hi, I have noticed a bug with the student builder / session builder. Somehow, all students share the same sessions and there are duplicates when it comes to the session.
As below, only alice has been given 1 session with fee of $88 and benson has been given a session with default fee of $40
image
image

However, if we look at the model generated, everyone has the **same** session and there every session created creates an additional default session as well, so somehow everyone has the same 4 session.
image

You can replicate this error by going to line 29 of email command test and inserting a breakpoint and checking the model value out.
image

### PR DESCRIPTION
**Pull request by samleewy**
Resolve #109 - Student/SessionBuilder bug

1. Removed unintended static `DEFAULT_SESSION`, replaced with new ArrayList for each new `StudentBuilder`
2. `withSession` renamed to `addSession`. To add a **list of sessions** into `StudentBuilder`, use `withListOfSessions` (to add on to current list), or `withNewListOfSessions` (for a clean slate of session list). These two methods have been added previously.
3. `EditStudentDescriptorBuilder` has been edited to include sessions as well (future-proofing).

### CODE REVIEW

File: src/test/java/seedu/address/testutil/TypicalStudents.java [hunk 1]
```diff
@@ -31,15 +31,15 @@
...
+                        .addSession(
                                 new SessionBuilder().withSessionDate("2020-01-01", "12:00").build()
                         )
             .build();
     public static final Student BENSON = new StudentBuilder().withName("Benson Meier")
             .withAddress("311, Clementi Ave 2, #02-25")
             .withEmail("johnd@example.com").withPhone("98765432")
             .withStudyLevel("Primary 2").withGuardianPhone("81902144").withRelationship("Father")
-                        .withSession(
+                        .addSession(
```
Comment (enhao25) [inline src/test/java/seedu/address/testutil/TypicalStudents.java]: Only one comment, I was thinking the indentation for the addSession(withSession previously) was abit weird and should have the same lvl of indentation with withStudyLevel instead. Do you think it would be better if we did that?

**Review by enhao25 — APPROVED** [review]
Great work! Solves the issue perfectly. Only had 1 minor comment.

File: src/test/java/seedu/address/testutil/TypicalStudents.java (hunk 1 above)
Comment (samleewy) [reply src/test/java/seedu/address/testutil/TypicalStudents.java]: Oh yes, i also found the indentation weird as well. Will make the change, thanks!!

**Review by JonahhGohh — APPROVED** [review]
LGTM! 💯
